version: 0.1
phases:
  install:
    commands:
      - cd app && npm install
      - aws cloudformation package --template-file samTemplate1.yaml --s3-bucket deployment-zip-files 
                                   --output-template-file samTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml