service: ci-test-service
provider:
  name: aws
  runtime: nodejs6.10
plugins:
  - serverless-offline
package:
  include:
    - node_modules/**
functions:
  generate:
    handler: handler.handler # required, handler set in AWS Lambda
    events:
      - http:
          path: app2
          method: get
  display:
    handler: second.handler # required, handler set in AWS Lambda
    events:
      - http:
          path: disp
          method: get
  ffinvok:
    handler: function-in-folder/index.handler # required, handler set in AWS Lambda
    events:
      - http:
          path: disp/folder
          method: get
resources:
  Resources:
    makyajDeleteJob:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: handler.handler
        Runtime: nodejs6.10
        CodeUri: .
        Description: ''
        MemorySize: 128
        Timeout: 3
        Role: 'arn:aws:iam::086588549640:role/service-role/lambdaUser'
        Events:
          Api1:
            Type: Api
            Properties:
              Path: '/jobs/{jobId}'
              Method: DELETE
        Environment:
          Variables:
            MONGODB_ATLAS_CLUSTER_URI: >-
              mongodb://lambdaUser:rABjR5yxsmyPy2MN@cluster0-shard-00-00-gw4c5.mongodb.net:27017,cluster0-shard-00-01-gw4c5.mongodb.net:27017,cluster0-shard-00-02-gw4c5.mongodb.net:27017/makyaj?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin
