version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Node dependencies
          command: cd app1 && npm install
      - run:
          name: Deploy to AWS
          command: npm run deploy


