# service: function-two
# provider:
#   name: aws
#   runtime: nodejs6.10
# plugins:
#   - serverless-offline
# functions:
#   generate:
#     handler: handler.handler # required, handler set in AWS Lambda
#     events:
#       - http:
#           path: app2
#           method: get
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  testCi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::086588549640:role/service-role/lambdaUser'
